config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end
  namespace :account do
    resources :groups
    resources :posts
  end
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :posts, :dependent => :destroy
  validates :title, presence: true
  has_many :group_relationships
  has_many :members, through: :group_relationships, source: :user

  scope :recent, -> { order("updated_at DESC") }
end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :content, presence: true

  scope :recent, -> { order("created_at DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :group_relationships
  has_many :participated_groups, :through => :group_relationships, :source => :group

  def is_member_of?(group)
    participated_groups.include?(group)
  end

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups.recent.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      current_user.join!(@group)
      redirect_to groups_path, notice: "Create Success"
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, alert: "Group deleted"
  end

  def join
    @group = Group.find(params[:id])

    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "加入本討論版成功！"
    else
      flash[:warning] = "你已經是本討論版成員了！"
    end

    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])

    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "已退出本討論版"
    else
      flash[:warning] = "你不是本討論版成員"
    end
    
    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end

  def find_group_and_check_permission
    @group = Group.find(params[:id])
    if current_user != @group.user
      redirect_to root_path, alert: "You have no permission"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :find_post_and_check_permission, :only => [:edit, :update, :destroy]

  def new
    @group = Group.find(params[:group_id])
    @post = Post.new
  end

  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)
    @post.group = @group
    @post.user = current_user
    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to group_path(@group), notice: "Update Success"
    else
      render :edit
    end    
  end

  def destroy
    @post.destroy
    redirect_to group_path(@group), alert: "Post deleted"
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_post_and_check_permission
    @group = Group.find(params[:group_id])
    @post = Post.find(params[:id])
    if current_user != @post.user
      redirect_to group_path(@group), alert: "You have no permission"
    end
  end
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def is_current_owner_logged_in?(owned)
    current_user && current_user == owned.user
  end

  def is_current_user_belongs_to?(group)
    current_user && current_user.is_member_of?(group)
  end

  def render_group_description(group)
    simple_format(group.description)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_post_content(post)
    simple_format(post.content)
  end  
end

app/views/common/_flashes.html.haml
- if flash.any?
  - user_facing_flashes.each do |key, value|
    %div.alert.alert-dismissable{:class => "alert-#{flash_class(key)}"}
      %button.close{"data-dismiss" => 'alert'}x
      = value

app/views/common/_footer.html.haml
%footer.container{:style => "position: fixed; bottom: 0px; width: 100%;"}
  %p.text-center 
    Copyright ©2018 Rails101
    %br 
    Design by 
    %a{:href => "http://courses.growthschool.com/courses/rails-101/", :target => "_blank"}xdite

app/views/common/_navbar.html.haml
%nav.navbar.navbar-default{:role => 'navigation'}
  %div.container-fluid
    %div.navbar-header
      %a.navbar-brand{:href => "/"} Rails 101
    %div.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if !current_user
          %li
            = link_to "註冊", new_user_registration_path
          %li
            = link_to "登入", new_user_session_path
        - else
          %li.dropdown
            %a.dropdown-toggle{"href": "#", "data-toggle": "dropdown"}
              Hi!, 
              =current_user.email
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to "My Groups", account_groups_path
              %li
                = link_to "My Posts", account_posts_path
              %li.divider
              %li
                = link_to "登出", destroy_user_session_path, method: :delete  

app/views/groups/_form.html.haml
= simple_form_for @group do |f|
  %div.form-group
    = f.input :title, input_html: { class: "form-control" }
    = f.input :description, input_html: { class: "form-control" }
  %div.form-actions
    = f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." }

app/views/groups/_group_item.html.haml
%tr
  %td 
    = link_to group.title, group_path(group)
  %td
    = render_group_description(group)
  %td
    = group.user.email
  %td
    - if is_current_owner_logged_in?(group)
      = link_to "Edit", edit_group_path(group), :class => "btn btn-sm btn-default"
      = link_to "Delete", group_path(group), class: "btn btn-sm btn-default", method: :delete, data: { confirm: "Are you sure?" }

app/views/groups/edit.html.haml
%div.col-md-4.col-md-offset-4
  %h2 編輯討論版
  %hr

  = render "form"
    

app/views/groups/index.html.haml
%div.col-md-12
  %div.group
    = link_to "New group", new_group_path, class: "btn btn-primary pull-right"
  %table.table.table-hover
    %thead
      %tr
        %td Title
        %td Description
        %td Creator
    %tbody
      = render :partial => "group_item", :collection => @groups, :as => :group
  %div.text-center
    = will_paginate @groups

app/views/groups/new.html.haml
%div.col-md-4.col-md-offset-4
  %h2 新增討論版
  %hr

  = render "form"

app/views/groups/show.html.haml
%div.col-md-12
  %div.group
    %span
      - if is_current_user_belongs_to?(@group)
        %label.label.label-success 群組成員
        - if current_user != @group.user
          = link_to "Quit Group", quit_group_path(@group), method: :post, class: "btn btn-default"
        = link_to "Write a Post", new_group_post_path(@group), class: "btn btn-default pull-right"
      - else
        %label.label.label-warning 不是群組成員
        = link_to "Join Group", join_group_path(@group), method: :post, class: "btn btn-default"

    - if is_current_owner_logged_in?(@group)
      = link_to "Edit", edit_group_path(@group), class: "btn btn-primary pull-right"
  %h2
    = @group.title
  %p
    = @group.description
  %table.table
    %thead
      %tr
        %th 文章內容
        %th 發表者
        %th 發表時間
    %tbody
      = render :partial => "posts/post_item", :collection => @posts, :as => :post
  %div.text-center
    = will_paginate @posts

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rails101
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div.container-fluid
      = render "common/navbar"
      = render "common/flashes"
      = yield
    = render "common/footer"

app/views/posts/_post_item.html.haml
%tr
  %td
    = render_post_content(post)
  %td
    = post.user.email
  %td
    = post.created_at
  %td
    - if is_current_owner_logged_in?(post)
      = link_to "Edit", edit_group_post_path(@group, post), :class => "btn btn-sm btn-default"
      = link_to "Delete", group_post_path(@group, post), class: "btn btn-sm btn-default", method: :delete, data: { confirm: "Are you sure?" }

app/views/posts/edit.html.haml
%h2.text-center 編輯文章
%div.col-md-4.col-md-offset-4
  = simple_form_for [@group, @post] do |f|
    %div.form-group
      = f.input :content, input_html: { class: "form-control" }
    %div.form-actions
      = f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary"

app/views/posts/new.html.haml
%h2.text-center 新增文章
%div.col-md-4.col-md-offset-4
  = simple_form_for [@group, @post] do |f|
    %div.form-group
      = f.input :content, input_html: { class: "form-control" }
    %div.form-actions
      = f.submit "Submit", disable_with: "Submitting...", class: "btn btn-primary"